//SYSTEM
export const SET_CURRENT_THEME = "SET_CURRENT_THEME";

//USER
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const GET_USERS_BY_NAME = "GET_USERS_BY_NAME";
export const SET_UPDATING_DISPLAY_NAME = "SET_UPDATING_DISPLAY_NAME";
export const UNSET_UPDATING_DISPLAY_NAME = "UNSET_UPDATING_DISPLAY_NAME";
export const IS_SIGNING_UP = "IS_SIGNING_UP";
export const UNSET_UPDATING_STATUS = "UNSET_UPDATING_STATUS";
export const SET_SIGN_UP_ERRORS = "SET_SIGN_UP_ERRORS";
export const CLEAR_SIGN_UP_ERRORS = "CLEAR_SIGN_UP_ERRORS";
export const SET_SIGN_IN_ERRORS = "SET_SIGN_IN_ERRORS";
export const CLEAR_SIGN_IN_ERRORS = "CLEAR_SIGN_IN_ERRORS";
export const SET_IS_SEARCHING_USERS = "SET_IS_SEARCHING_USERS";
export const UNSET_IS_SEARCHING_USERS = "UNSET_IS_SEARCHING_USERS";


//Boards
export const SET_IS_FETCHING_BOARDS = "SET_IS_FETCHING_BOARDS";
export const SET_BOARDS = "SET_BOARDS"; 
export const SET_IS_CREATING_BOARD = "SET_IS_CREATING_BOARD";


